cache:
  directories:
    - node_modules
language: node_js
script:
  - yarn lint
  - yarn test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then yarn semantic-release; fi'
node_js:
  - lts/*
env:
  global:
    secure: D1onfahvin6+8gnstOUEgbFLilgeIKPX8uMOIybJdytt8avyhX7WAKPdmchSV84RBh1y3u8/mAuohZkZKThunvJgPbaEtqcXA63v+FRvo2wSebPMmnMHmujVa1vYQxH3fS6Kk0HMyYZBy+3Ey0NwvUfNrM/2Ua9NiDk1+UAPXEjRTwKuo28bn86ZmOpwia22khVS3UWPGXWQLFuq/TKzl961n0SjjqZUEWtLZzBylWx5+DsyeCi2NHYuidXJgjHa0UiAUBFXnkPUBlJcKzM5OOW77YRpysQyG6XDVfwIiLqTEsh7jmQLdTIv8mIlh6EpNZrXv76S3jUdTBjKTglHuQTqzMVuGZS7vl5Tr2IDbuk4yX1qy+qKqC4F5RyD3JXc4t7solD2R/PnjoGZsR02rWPE3jOatm1u9VkNhUKMwuc3fADbbvukqW2WjoDJISlhCi01tlL5AeU5r3WNthkHm+7WmH67ca0pNcvXO/L8XyxpApG4hVHsCQarOu6R/YwYZaFvJfKRNlrxR3VExEhlgHwcCar+oMU2qSQfUmgRq/6zOX7ad6eJh65xy7h4euAIQbbZDOEpgLBJFZMh7vlyb1LUe3976s0YbhGv6mHKQGesyRHVK2lBaKSG4OwizeO8fuclCjQV0Oyrp6RJ9pWQNd0zFCovWHgs1TsRSCLUFKk=
