cache:
  directories:
    - node_modules
language: node_js
script:
  - yarn lint
  - yarn test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then yarn semantic-release; fi'
node_js:
  - lts/*
env:
  global:
    secure: IvSI6UxBIebAUGO/W9SQehLo1JRBM1mdQtjmB9dp+lc8B0T0NKBnmViIv92FixT7W95sRO6qWv9HDVZLDs0RxTwzWt9AjXplvoMtIWgZNeoUzv5hEwqrnSnXtqeUceSF7vqpi9OIOWS7GCiNP6ZQu8/Ow+D6wzfV/+7L1VsonJCeGT/JVyY4UikiK9CFSdT3h1HbSsooE6oEo00j7KSbl/bEwPlj97K804WZf/VONLv76+Xv+jjBMakxbgMqWnNrT/Y3v4akbLaZih0jAMZMnhP7OzoSRpNW4p7AkxGyK+qF7UpXZ0g3QK3iP14/UFJz9DftmcT4OTU1eF6dO8yrxDHRRABAfP3hrq07QIrJGg5BV+CNAkIFOkQ1RRss/f/vHjq3fmsGUsSYBz63qnTPylXdERxEP/RIv2JvyyO6gWS6EWTEElzUs/J50ipm30iuI7wkAhV6wV6y62yZhW9xrwZSNRZrDk6lH4mazuf6htTfeGeQazdnj4rWr/rrvl+vEt4HYt1SM1cvCASijXyqt4C3rtxJGZiCJBcsD0xbXh7KW0uZlE08K5STKWv+qd/9OjtD7+Twb7o+/LrZbJcd8hfU7nJXFnTNZEqx9BBCLDPu+dXARN6J5oa428dMNX1IZNOY8kxnpC0gpkCEkFCe5DSX89SraJGffqJ2Yicdx/o=
